class AddComunas < ActiveRecord::Migration[6.0]
  def change
    Comuna.create(comuna: 'Pudahuel', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Cerro Navia', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Las Condes', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Quilicura', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Conchalí', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Lo Barnechea', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Quinta Normal', region: 'Región Metropolitana')
    Comuna.create(comuna: 'El Bosque', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Lo Espejo', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Recoleta', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Estación Central', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Lo Prado', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Renca', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Huechuraba', region: 'Región Metropolitana')
    Comuna.create(comuna: 'San Miguel', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Independencia', region: 'Región Metropolitana')
    Comuna.create(comuna: 'San Joaquín', region: 'Región Metropolitana')
    Comuna.create(comuna: 'La Cisterna', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Ñuñoa', region: 'Región Metropolitana')
    Comuna.create(comuna: 'San Ramón', region: 'Región Metropolitana')
    Comuna.create(comuna: 'La Florida', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Pedro Aguirre Cerda', region: 'Región Metropolitana')
    Comuna.create(comuna: 'La Pintana', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Vitacura', region: 'Región Metropolitana')
    Comuna.create(comuna: 'La Granja', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Colina', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Peñaflor', region: 'Región Metropolitana')
    Comuna.create(comuna: 'San Bernardo', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Lampa', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Pirque', region: 'Región Metropolitana')
    Comuna.create(comuna: 'San José de Maipo', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Padre Hurtado', region: 'Región Metropolitana')
    Comuna.create(comuna: 'Puente Alto', region: 'Región Metropolitana')
  end
end
